list = ["pasda","asdasd","Lasdo","dsad","c"]
print(list[0:-1])
print("c" not in list)
print(len(list))
llll = list.append("SEXY RAFIN")
print(list)
print(len(list))
list.insert(2,"Shakil")
print(list)
list.remove("c")
print(list)
list.sort()
print(list)
list.reverse()
print(list)
list.pop()
print(list)
subj2 = list.copy()
print(subj2)
subj2.clear()
print(subj2)
position = list.index("Shakil")
print(position)
counter = list.count("Shakil")
print(counter)
